
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async state() : Promise<Result<Snapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async open(path: string) : Promise<Result<Snapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlock(totp: string) : Promise<Result<Snapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock", { totp }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lock() : Promise<Result<Snapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lock") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async nav(target: NavTarget | null) : Promise<Result<Snapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("nav", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async back() : Promise<Result<Snapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("back") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async forward() : Promise<Result<Snapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forward") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async up() : Promise<Result<Snapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("up") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async outdir(path: string) : Promise<Result<Snapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("outdir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * /api/extract: out falls back to the session out_dir, which is then set
 * to the resolved value (python `(args.get("out") or SESSION.out_dir or "")`).
 */
async extract(ids: string[] | null, out: string | null) : Promise<Result<ExtractResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract", { ids, out }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async verify() : Promise<Result<VerifyResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async totp(b32: string, digits: number | null) : Promise<Result<TotpResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("totp", { b32, digits }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pack(src: string | null, dst: string | null, digits: number | null, b32: string | null, profile: string | null) : Promise<Result<PackResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack", { src, dst, digits, b32, profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async demo(dst: string | null, digits: number | null, profile: string | null) : Promise<Result<DemoResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("demo", { dst, digits, profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async add(paths: string[]) : Promise<Result<AddResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportPassbox(out: string, passphrase: string | null) : Promise<Result<ExportPassboxResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_passbox", { out, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * GET /api/selftest returns the plain string array (no state snapshot).
 */
async selftest() : Promise<Result<SelftestResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("selftest") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * /api/browse via tauri-plugin-dialog (replaces the Win32 comdlg port).
 * mode: "file" | "dir" | "save"; filetypes: [[name, pattern], …].
 * Cancellation yields an empty list (python dialog semantics).
 */
async browse(mode: string | null, title: string | null, initial: string | null, filetypes: ([string, string])[] | null, defaultext: string | null) : Promise<Result<BrowseResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browse", { mode, title, initial, filetypes, defaultext }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 红点退出: reply first, then exit the app (python threading.Timer(0.3)).
 */
async shutdown() : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("shutdown") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * P0#3 probe: constant-memory chunked read of an arbitrary-size file with
 * progress pushed through a Channel (P4 wires the big-file path to this).
 */
async readFileProgress(path: string, onChunk: TAURI_CHANNEL<ReadProgress>) : Promise<Result<number, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file_progress", { path, onChunk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AddResult = { count: number; state: Snapshot }
export type ApiError = { 
/**
 * Server-level code string; empty for plain failures.
 */
code: string; message: string }
export type BrowseResult = { paths: string[] }
/**
 * /api/demo payload (C# MakeDemo — no vault_id/generation/entries).
 */
export type DemoInfo = { b32: string; digits: number; uri: string; matrix: number[][] | null; dst: string }
export type DemoResult = { demo: DemoInfo; state: Snapshot }
export type ExportPassboxResult = { out: string; state: Snapshot }
export type ExtractResult = { count: number; out: string; state: Snapshot }
export type Info = { name: string; path: string; vault_id: string; generation: number; files: number | null; slots_digits: number[]; status: string }
export type Item = { id: string; name: string; is_dir: boolean; size: number; size_h: string; modified: number; modified_h: string }
/**
 * /api/nav target (C# reads the raw JSON element; this typed shape covers
 * every payload the frontend emits).
 */
export type NavTarget = { dir: string | null; path: string | null }
/**
 * /api/pack payload (C# DoPack).
 */
export type PackInfo = { b32: string; digits: number; uri: string; matrix: number[][] | null; dst: string; vault_id: string; generation: number; entries: number }
export type PackResult = { pack: PackInfo; state: Snapshot }
/**
 * Progress event pushed while streaming a file read in fixed-size chunks.
 */
export type ReadProgress = { read: number; total: number }
export type SelftestResult = { lines: string[] }
/**
 * Fields and key names exactly mirror C# WriteSnapshot (frontend contract).
 */
export type Snapshot = { phase: string; info: Info | null; path: string; can_back: boolean; can_forward: boolean; can_up: boolean; items: Item[]; out_dir: string; home: string; qr_ok: boolean }
export type TAURI_CHANNEL<TSend> = null
export type TotpResult = { code: string; state: Snapshot }
export type VerifyResult = { message: string; state: Snapshot }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
