# -*- coding: utf-8 -*-
"""ASTBOX v1.0 protocol constants (ASTBOX-v1.0-01-Core-Format.txt and friends)."""

HEADER_MAGIC = b"ASTBOX"
FOOTER_MAGIC = b"ASTBOXF1"
VERSION = 1

HEADER_SIZE = 128
KEY_SLOT_SIZE = 192
FOOTER_SIZE = 112
MIN_KEY_SLOT_COUNT = 1
MAX_KEY_SLOT_COUNT = 16

VAULT_ID_SIZE = 16
SLOT_ID_SIZE = 16
VAULT_KEY_SIZE = 32
SALT_SIZE = 32
WRAP_NONCE_SIZE = 24
WRAPPED_VAULT_KEY_SIZE = 48
MAC_SIZE = 16

METADATA_NONCE_SIZE = 24
METADATA_TAG_SIZE = 16
DATA_NONCE_SIZE = 24
DATA_TAG_SIZE = 16
# Fixed per-record overhead: FileID(16)+ChunkIndex(8)+PlaintextLength(4)
# +DataNonce(24)+Tag(16) == 68
DATA_RECORD_OVERHEAD = 68

MAX_CHUNK_PLAINTEXT = 1048576  # 1 MiB

# Credential types
CRED_TYPE_PASSWORD = 0x0001
CRED_TYPE_TOTP = 0x0002

# KDF profiles -> (memory KiB, time cost, parallelism)
KDF_PROFILE_HIGH = 0x0001
KDF_PROFILE_MEMORY_CONSTRAINED = 0x0002
ARGON2_PROFILES = {
    KDF_PROFILE_HIGH: (262144, 3, 1),
    KDF_PROFILE_MEMORY_CONSTRAINED: (65536, 3, 1),
}

# Fixed ASCII domain-separation labels
LABEL_KDF = b"ASTBOX-KDF-v1"
LABEL_WRAP = b"ASTBOX-WRAP-v1"
LABEL_HKDF_SALT = b"ASTBOX-HKDF-SALT-v1"
LABEL_HDRM = b"ASTBOX-HDRM-v1"
LABEL_META = b"ASTBOX-META-v1"
LABEL_DATA = b"ASTBOX-DATA-v1"
LABEL_SLOTM = b"ASTBOX-SLOTM-v1"
LABEL_FOOT = b"ASTBOX-FOOT-v1"
LABEL_HEADER_MAC = b"ASTBOX-HEADER-MAC-v1"
LABEL_SLOT_MAC = b"ASTBOX-SLOT-MAC-v1"
LABEL_METADATA = b"ASTBOX-METADATA-v1"
LABEL_FOOTER_MAC = b"ASTBOX-FOOTER-MAC-v1"

# Metadata CBOR top-level keys
META_KEY_VERSION = 1
META_KEY_ROOT = 2
META_KEY_ENTRIES = 3
META_KEY_CREATED = 4
META_KEY_MODIFIED = 5

# Entry CBOR keys
ENTRY_KEY_FILEID = 1
ENTRY_KEY_PARENT = 2
ENTRY_KEY_TYPE = 3
ENTRY_KEY_NAME = 4
ENTRY_KEY_SIZE = 5
ENTRY_KEY_DATA_START = 6
ENTRY_KEY_DATA_LENGTH = 7
ENTRY_KEY_MODIFIED = 8
ENTRY_KEY_MODE = 9

TYPE_DIRECTORY = 0
TYPE_FILE = 1

ROOT_DIRECTORY_ID = b"\x00" * 16

# TOTP
TOTP_PERIOD = 30
TOTP_T0 = 0

MAX_DIRECTORY_DEPTH = 4096
